# Generated by Django 4.2.7 on 2023-11-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwashmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('typeofvehicle', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Null', 'not specified')], default='Null', max_length=10)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
